In [1]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [7]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [8]:
# cost/Loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small Leaning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# Launch the graph in a session
sess = tf.Session()

In [17]:
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "cost: ", cost_val, "\nPrediction:\n", hy_val, 
              "\nweight,bias:\n", sess.run(w1), sess.run(w2), sess.run(w3), sess.run(b))

0 cost:  14863.102 
Prediction:
 [44.617683 53.858734 53.068172 55.881405 42.795128] 
weight,bias:
 [0.9511895] [0.4951529] [-0.22943561] [0.3865654]
10 cost:  0.8644347 
Prediction:
 [152.4603  183.48154 180.78563 194.96303 141.66527] 
weight,bias:
 [1.2152476] [0.75844747] [0.03767527] [0.38962677]
20 cost:  0.7267655 
Prediction:
 [152.78447 183.87518 181.17137 195.38359 141.96608] 
weight,bias:
 [1.2162168] [0.75891685] [0.03863841] [0.38962862]
30 cost:  0.72516507 
Prediction:
 [152.78331 183.87779 181.17186 195.38464 141.96866] 
weight,bias:
 [1.2163895] [0.75859183] [0.03879604] [0.38962117]
40 cost:  0.72355026 
Prediction:
 [152.78117 183.87926 181.17116 195.3844  141.97034] 
weight,bias:
 [1.2165589] [0.7582652] [0.03895109] [0.38961372]
50 cost:  0.721972 
Prediction:
 [152.77905 183.88069 181.1705  195.38419 141.972  ] 
weight,bias:
 [1.2167281] [0.7579394] [0.03910588] [0.38960627]
60 cost:  0.72038734 
Prediction:
 [152.77693 183.88211 181.16978 195.38393 141.97365] 
wei

740 cost:  0.6292795 
Prediction:
 [152.64464 183.97101 181.12697 195.37051 142.07553] 
weight,bias:
 [1.2269866] [0.73728144] [0.0493711] [0.38909218]
750 cost:  0.6281576 
Prediction:
 [152.64288 183.97221 181.1264  195.37036 142.0769 ] 
weight,bias:
 [1.2271166] [0.73700684] [0.04951418] [0.38908473]
760 cost:  0.62703097 
Prediction:
 [152.64108 183.97339 181.12582 195.37021 142.07823] 
weight,bias:
 [1.2272455] [0.7367329] [0.04965706] [0.38907728]
770 cost:  0.6259073 
Prediction:
 [152.63933 183.97461 181.12526 195.37006 142.07957] 
weight,bias:
 [1.2273742] [0.7364598] [0.04979985] [0.38906983]
780 cost:  0.6248044 
Prediction:
 [152.63756 183.97577 181.12468 195.36989 142.08092] 
weight,bias:
 [1.2275023] [0.7361871] [0.04994232] [0.38906237]
790 cost:  0.6236917 
Prediction:
 [152.6358  183.97696 181.1241  195.36974 142.08226] 
weight,bias:
 [1.22763] [0.73591524] [0.05008481] [0.38905492]
800 cost:  0.6226075 
Prediction:
 [152.63405 183.97812 181.12354 195.36955 142.08357] 

1320 cost:  0.5719792 
Prediction:
 [152.54858 184.03537 181.09563 195.36261 142.14757] 
weight,bias:
 [1.2337105] [0.7224025] [0.05742279] [0.38866004]
1330 cost:  0.5711192 
Prediction:
 [152.54706 184.0364  181.09512 195.3625  142.14871] 
weight,bias:
 [1.233813] [0.7221637] [0.05755745] [0.3886526]
1340 cost:  0.5702666 
Prediction:
 [152.54552 184.03743 181.09462 195.36238 142.14984] 
weight,bias:
 [1.2339152] [0.72192544] [0.05769186] [0.38864514]
1350 cost:  0.5694187 
Prediction:
 [152.544   184.03845 181.09412 195.36227 142.15097] 
weight,bias:
 [1.2340165] [0.72168785] [0.05782626] [0.3886377]
1360 cost:  0.56857294 
Prediction:
 [152.54247 184.03947 181.09363 195.36217 142.1521 ] 
weight,bias:
 [1.2341179] [0.72145075] [0.05796047] [0.38863024]
1370 cost:  0.5677278 
Prediction:
 [152.54094 184.04048 181.09311 195.36205 142.15321] 
weight,bias:
 [1.2342186] [0.7212142] [0.05809455] [0.3886228]
1380 cost:  0.5668877 
Prediction:
 [152.53943 184.0415  181.09262 195.36195 142.1

1940 cost:  0.5255791 
Prediction:
 [152.46033 184.09431 181.06657 195.35713 142.21182] 
weight,bias:
 [1.2392904] [0.7086172] [0.06552589] [0.38818604]
1950 cost:  0.5249237 
Prediction:
 [152.45901 184.09518 181.06612 195.35707 142.21277] 
weight,bias:
 [1.2393678] [0.70841104] [0.06565275] [0.3881783]
1960 cost:  0.5242837 
Prediction:
 [152.4577  184.09607 181.0657  195.35701 142.21371] 
weight,bias:
 [1.2394453] [0.7082054] [0.06577951] [0.38817054]
1970 cost:  0.52364284 
Prediction:
 [152.45639 184.09694 181.06528 195.35695 142.21465] 
weight,bias:
 [1.2395227] [0.70799994] [0.06590602] [0.3881628]
1980 cost:  0.52300125 
Prediction:
 [152.4551  184.0978  181.06482 195.35687 142.21556] 
weight,bias:
 [1.2395993] [0.70779514] [0.06603251] [0.38815504]
1990 cost:  0.5223576 
Prediction:
 [152.45378 184.09868 181.06439 195.35681 142.21649] 
weight,bias:
 [1.2396756] [0.7075908] [0.06615894] [0.3881473]
2000 cost:  0.5217265 
Prediction:
 [152.4525  184.09955 181.06396 195.35675 142