In [14]:
import tensorflow as tf

x_data = [[1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5], [1,2,5,6], [1,6,6,6], [1,7,7,7]]

y_data = [[0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0], [1,0,0], [1,0,0]]

In [15]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])

# Y의 개수가 클래스의 개수
nb_classes = 3
# Shape 주의!                  [X:들어오는 값, Y:나가는 값]
W = tf.Variable(tf.random_normal([4, nb_classes], name='weight'))
#                              [Y:나가는 값]
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [16]:
# tf.nn.softmax computes softmax activations
# softmax = exp(Logits) / reduce_sum(exp(Logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [17]:
# Cross entropy cost/ Loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [22]:
# Launch graph
sess = tf.Session()

#with tf.Session() as sess:
sess.run(tf.global_variables_initializer())
    
for step in range(2001):
    sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
    if step % 200 == 0:
         print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

0 7.7921066
200 0.5672696
400 0.4604665
600 0.3817428
800 0.307855
1000 0.24518806
1200 0.22121336
1400 0.2015673
1600 0.18502909
1800 0.17091668
2000 0.15873787


In [26]:
# 출력 : Testing & One-hot encoding
a = sess.run(hypothesis, feed_dict= {X: [[1, 11, 7, 9]]})
#print(a, sess.run(tf.arg_max(a,1)))    // arg_max  -> argmax로 변경됨 by Version
print(a, sess.run(tf.argmax(a,1)))

print('-------------------')

b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
print(b, sess.run(tf.argmax(b,1)))

print('-------------------')

c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
print(c, sess.run(tf.argmax(c,1)))

print('-------------------') 

all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
print(all, sess.run(tf.argmax(all,1)))

[[9.0885879e-03 9.9090284e-01 8.5372658e-06]] [1]
-------------------
[[0.8168941  0.17003942 0.01306647]] [0]
-------------------
[[1.3321367e-08 3.5533306e-04 9.9964464e-01]] [2]
-------------------
[[9.0885879e-03 9.9090284e-01 8.5372658e-06]
 [8.1689417e-01 1.7003942e-01 1.3066473e-02]
 [1.3321367e-08 3.5533306e-04 9.9964464e-01]] [1 0 2]
